ThaiViet Smile Travel/Controllers/BaseController.cs
using System;
using System.Globalization;
using System.IO;
using System.Threading;
using System.Web.Mvc;
using System.Web.Routing;

using ThaiViet_Smile_Travel.Common;

namespace ThaiViet_Smile_Travel.Controllers
{
    public class BaseController : Controller
    {
        protected override void Initialize(RequestContext requestContext)
        {
            base.Initialize(requestContext);
            if (CommonConstants.CurrentCulture != null)
            {
                Thread.CurrentThread.CurrentCulture = new CultureInfo(CommonConstants.CurrentCulture.ToString());
                Thread.CurrentThread.CurrentUICulture = new CultureInfo(CommonConstants.CurrentCulture.ToString());
            }
            else
            {
                Thread.CurrentThread.CurrentCulture = new CultureInfo("th");
                Thread.CurrentThread.CurrentUICulture = new CultureInfo("th");
            }
            double khach = 0;
            TextReader tr = new StreamReader(Server.MapPath("~/luottruycap.txt"));
            khach = Convert.ToDouble(tr.ReadLine());
            tr.Close();
            tr.Dispose();
            try
            {
                khach++;
                TextWriter tw = new StreamWriter(Server.MapPath("~/luottruycap.txt"));
                tw.Write(khach);
                tw.Close();
                tw.Dispose();
            }
            catch (Exception)
            {
            }
            ViewBag.LuotTruyCap = khach.ToString();
        }

        //change culture
        public ActionResult ChangeCulture(string valueCulture, string returnUrl)
        {
            Thread.CurrentThread.CurrentCulture = new CultureInfo(valueCulture);
            Thread.CurrentThread.CurrentUICulture = new CultureInfo(valueCulture);

            CommonConstants.CurrentCulture = valueCulture;
            return Redirect(returnUrl);
        }
    }
}

ThaiViet Smile Travel/Controllers/TourController.cs
using System;
using System.Linq;
using System.Web.Mvc;

using PagedList;

using ThaiVietSmileTravel.Models.Framework;

namespace ThaiViet_Smile_Travel.Controllers
{
    public class TourController : BaseController
    {
        private TVSTravelDbContext db = new TVSTravelDbContext();

        // GET: Tour

        public ActionResult Index(int? categoryId, int page = 1, int pageSize = 6)
        {
            try
            {
                var category = db.tbl_Categories
                    .Find(categoryId);
                if (category != null)
                {
                    ViewBag.TitleCategory = category.TenVN;
                    var query = db.tbl_Tour
                        .Where(x => x.CategoryId == categoryId && x.IsActive)
                        .OrderByDescending(x => x.NgayTao)
                        .ToList();
                    var results = query.ToPagedList(page, pageSize);
                    return View(results);
                }
                else
                {
                    return RedirectToAction("NotFound", "Home");
                }
            }
            catch (Exception)
            {
                return RedirectToAction("NotFound", "Home");
            }
            return View();
        }

        public ActionResult Detail(int? id)
        {
            if (id != 0)
            {
                var result = db.tbl_Tour
                    .Where(x => x.Id == id)
                    .FirstOrDefault();
                return View(result);
            }
            else
            {
                return RedirectToAction("NotFound", "Home");
            }
            return View();
        }
    }
}

ThaiViet Smile Travel/Views/Shared/CartInfo.cshtml
@model List<ThaiViet_Smile_Travel.Models.CardItemModel>
@{
    ViewBag.Title = "Card";
}
<div class="shopcard">
    <a href="@Url.Action("Index","Card")">
        <span class="glyphicon glyphicon-shopping-cart"></span>
        <span class="">@ThaiVietSmileTravel.Globalization.Resource.TitleShopCard: @Model.Count @ThaiVietSmileTravel.Globalization.Resource.lblTour</span>
    </a>
</div>

ThaiViet Smile Travel/Views/Shared/_AdBanner.cshtml
@model IEnumerable<ThaiVietSmileTravel.Models.Framework.tbl_Banner>
@{
    ViewBag.Title = "_AdBanner";
}

<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        @foreach (var item in Model)
        {
            if (item.Id == 1)
            {
                <div class="item active">
                    <a class="slide-image" href="@item.UrlTour"><img class="slide-image" style="height: 400px;" src="@item.HinhAnh" alt=""></a>
                    @*<img class="slide-image" src="~/Content/img/ca-mau.png" alt="">*@
                </div>
            }

            if (item.Id == 2)
            {
                <div class="item">
                    <a class="slide-image" href="@item.UrlTour"><img class="slide-image" style="height: 400px;" src="@item.HinhAnh" alt=""></a>
                </div>
            }
            if (item.Id == 3)
            {
                <div class="item">
                    <a class="slide-image" href="@item.UrlTour"><img class="slide-image" style="height: 400px;"  src="@item.HinhAnh" alt=""></a>
                </div>
            }
        }
    </div>
    <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
    </a>
    <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
    </a>
</div>

ThaiViet Smile Travel/Views/Shared/_Category.cshtml
@{
    ViewBag.Title = "Category";
}

<div class="block block-side-nav m2 first" style="margin-top:20px">
    <div class="block-title" style="margin-bottom:0px">
        <h4><a style="list-style: none;text-decoration: none;" href="@Url.Action("Index", "Home")">@ThaiVietSmileTravel.Globalization.Resource.titleHome</a></h4>
    </div>
    <div class="block-content-cat">
        <ul class="sf-menu-phone2">

            @*<li class="level0 nav-1 first level-top"><a href="@Url.Action("Index", "Tour", new {categoryId = 1 })">@ThaiVietSmileTravel.Globalization.Resource.TourNorthern</a></li>*@

            <li class="level0 nav-1 first level-top"><a href="@Url.Action("About", "Home")">@ThaiVietSmileTravel.Globalization.Resource.TitleAbout</a></li>

            <li class="level0 nav-1 first level-top"><a href="@Url.Action("Contact", "Home")">@ThaiVietSmileTravel.Globalization.Resource.TitleContact</a></li>

            @*<li class="level0 nav-1 first level-top"><a href="@Url.Action("Index", "Tour", new {categoryId = 4 })">@ThaiVietSmileTravel.Globalization.Resource.TourForeign</a></li>*@
        </ul>
    </div>
</div>

ThaiViet Smile Travel/Views/Shared/_Footer.cshtml
@{
    ViewBag.Title = "_Footer";
}

<footer>
    <div class="row">
        <div class="col-lg-12 footer">
            <div class="textfooter">
                <p>THAIVIET SMILE TRAVEL CO., LTD</p>
                <p>268 Nguyen Xien Str., Thanh Xuan Dist., Hanoi, Vietnam.</p>
                <p>12 Bui Chat Str., Lien Chieu Dist., Danang, Vietnam.</p>
                <p>Copyright &copy; ThachSungDo 2017</p>
            </div>
        </div>
    </div>
</footer>

ThaiViet Smile Travel/Views/Shared/_Head.cshtml
@{
    ViewBag.Title = "head";
}

<div class="col-md-9" style="height: 100px;">
    <img src="~/Content/img/logo-w-800.png" class="img-responsive" />
</div>
<div class="col-md-3">
    <span style="float: right; margin-bottom: 10px;">
       
        <a href="@Url.Action("ChangeCulture", "Base", new { valueCulture = "th" , returnUrl = Request.RawUrl})">
            <img src="~/Content/img/th.png" />
        </a>
        <a href="@Url.Action("ChangeCulture", "Base", new { valueCulture = "vi" , returnUrl = Request.RawUrl})">
            <img src="~/Content/img/vn.png" />
        </a>
        <a href="@Url.Action("ChangeCulture", "Base", new { valueCulture = "en" , returnUrl = Request.RawUrl})">
            <img src="~/Content/img/en.png" />
        </a>
    </span>
</div>

ThaiViet Smile Travel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>@ViewBag.Title - @ThaiVietSmileTravel.Globalization.Resource.titleTravel</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <div class="container">
        <div class="row" style="margin-top: 10px;">
            @Html.Partial("_Head")
        </div>
    </div>
    <div class="container">
        <div class="background-content">
            <div class="row">
                <div class="col-md-12">
                    @{Html.RenderAction("_AdBanner", "Home");}
                    @*@Html.Partial("_Menu")*@
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <div class="sub-left-menu">
                        @*@{ Html.RenderAction("CartInfo", "Home");}*@
                        @Html.Partial("_Category")
                        @*@Html.Partial("_SpecialTour")*@

                        <div class="cbp-spmenu cbp-spmenu-vertical" style="margin-top: 20px;">
                            <img src="~/Content/img/hotline.png" class="img-responsive" />
                            <script type="text/javascript" src="https://secure.skypeassets.com/i/scom/js/skype-uri.js"></script>
                            @*<div id="SkypeButton_Call_thaivietsmiletravel_1">
                                <script type="text/javascript">
                                    Skype.ui({
                                        "name": "dropdown",
                                        "element": "SkypeButton_Call_thaivietsmiletravel_1",
                                        "participants": ["thaivietsmiletravel"],
                                        "imageSize": 24
                                    });
                                </script>
                            </div>*@
                            <div class='fb-like' data-action='like' data-href='' data-layout='button_count' data-share='true' data-show-faces='false' data-width='520' ></div>
                        </div>
                        <div style="background-color: greenyellow; margin-top: 20px;border-radius: 5px;padding: 15px;height: 50px; margin-bottom: 20px;">
                            <label style="color: blue;"><i class="glyphicon glyphicon-signal blue"></i> @ThaiVietSmileTravel.Globalization.Resource.lblCountVisistor: @ViewBag.LuotTruyCap</label>
                        </div>
                    </div>

                </div>
                <div class="col-md-9">
                    <div class="col-md-12 container-right">
                        <!-- Page Content -->
                        @RenderBody()
                    </div>
                </div>
            </div>

            <!-- Footer -->
            @Html.Partial("_Footer")
        </div>
    </div>
    <!-- /.container -->
    <!-- jQuery -->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ThaiViet Smile Travel/Views/Shared/_Menu.cshtml
@{
    ViewBag.Title = "_Menu";
}

<nav class="navbar navbar-default" role="navigation">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="@Url.Action("Index", "Home")"><span class="glyphicon glyphicon-home "></span></a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
            <li>
                <a href="@Url.Action("About", "Home")">@ThaiVietSmileTravel.Globalization.Resource.TitleAbout</a>
            </li>
            <li>
                <a href="@Url.Action("Contact", "Home")">@ThaiVietSmileTravel.Globalization.Resource.TitleContact</a>
            </li>
        </ul>
        @*@using (Html.BeginForm("Index", "Home", FormMethod.Get))
        {
            <div class="col-sm-3 col-md-3 pull-right" style="margin-top: 10px;">
                <form class="navbar-form" role="search">
                    <div class="input-group">
                        <input type="text" class="form-control" name="searchtour" placeholder="@ThaiVietSmileTravel.Globalization.Resource.lblSearch" name="q">
                        <div class="input-group-btn">
                            <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                        </div>
                    </div>
                </form>

            </div>
        }*@
    </div>
</nav>

ThaiViet Smile Travel/Views/Shared/_Search.cshtml
@{
    ViewBag.Title = "@ThaiVietSmileTravel.Globalization.Resource.lblSearch";
}

<form class="navbar-form navbar-left" role="search" action="/Product/Search">
    <div class="input-group input-group-lg">
        <input id="search" name="keywords" class="form-control" placeholder="@ThaiVietSmileTravel.Globalization.Resource.lblSearch" />
        <span class="input-group-btn">
            <button class="btn btn-default" type="submit"><span class="glyphicon glyphicon-search"></span></button>
        </span>
    </div>
</form>

ThaiViet Smile Travel/Views/Shared/_SpecialTour.cshtml
@{ 
    ViewBag.Title = "SpecialTour";
}
<div class="cbp-spmenu cbp-spmenu-vertical">
    <h3>Tour đặc biệt</h3>
    <img src="~/Content/img/Background.jpg" class="img-responsive" />
</div>