ThaiViet Smile Travel/Controllers/CardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Web.Script.Serialization;

using ThaiVietSmileTravel.Common;
using ThaiVietSmileTravel.Globalization;
using ThaiVietSmileTravel.Models.Framework;

using ThaiViet_Smile_Travel.Common;
using ThaiViet_Smile_Travel.Models;
using System.Globalization;

namespace ThaiViet_Smile_Travel.Controllers
{
    public class CardController : BaseController
    {
        private TVSTravelDbContext db = new TVSTravelDbContext();

        // GET: Card
        public ActionResult Index()
        {
            var card = Session[CommonConstants.CardSession];
            var list = new List<CardItemModel>();
            if (card != null)
            {
                list = (List<CardItemModel>)card;
            }

            return View(list);
        }

        public ActionResult AddItem(int tourId, int soLuong)
        {
            var tour = db.tbl_Tour.Find(tourId);
            var card = Session[CommonConstants.CardSession];
            if (card != null)
            {
                var list = (List<CardItemModel>)card;
                if (list.Exists(x => x.Tour.Id != tourId))
                {
                    foreach (var temp in list)
                    {
                        if (temp.Tour.Id == tourId)
                        {
                            return RedirectToAction("index");
                        }
                    }
                    var item = new CardItemModel();
                    item.Tour = tour;
                    item.SoNguoi = soLuong;

                    list.Add(item);
                }
                Session[CommonConstants.CardSession] = list;
            }
            else
            {
                var item = new CardItemModel();
                item.Tour = tour;
                item.SoNguoi = soLuong;
                var list = new List<CardItemModel>();
                list.Add(item);
                Session[CommonConstants.CardSession] = list;
            }
            return RedirectToAction("index");
        }

        public JsonResult Update(string cardModel)
        {
            var jsoncard = new JavaScriptSerializer().Deserialize<List<CardItemModel>>(cardModel);
            var sessionCard = (List<CardItemModel>)Session[CommonConstants.CardSession];

            foreach (var item in sessionCard)
            {
                var jsonitem = jsoncard.SingleOrDefault(x => x.Tour.Id == item.Tour.Id);
                if (jsonitem != null)
                {
                    item.SoNguoi = jsonitem.SoNguoi;
                }
            }
            Session[CommonConstants.CardSession] = sessionCard;
            return Json(new
            {
                status = true
            });
        }

        public JsonResult Delete(int id)
        {
            var sessionCard = (List<CardItemModel>)Session[CommonConstants.CardSession];
            sessionCard.RemoveAll(x => x.Tour.Id == id);
            if (sessionCard.Count == 0)
            {
                Session[CommonConstants.CardSession] = null;
            }
            else
            {
                Session[CommonConstants.CardSession] = sessionCard;
            }
            return Json(new
            {
                status = true
            });
        }

        [ValidateInput(false)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult OrderTour(string tenKH, string diaChi, string soDT, string email, string datetimepickerOrder, string ghiChu)
        {
            var cart = (List<CardItemModel>)Session[CommonConstants.CardSession];
            var admin = db.tbl_Account.FirstOrDefault();
            if (!string.IsNullOrEmpty(tenKH) && !string.IsNullOrEmpty(diaChi) && !string.IsNullOrEmpty(soDT))
            {
                var order = new tbl_Orders();
                order.TenKH = tenKH;
                order.DiaChi = diaChi;
                order.SoDT = soDT;
                order.Email = email;
                order.NgayDat = DateTime.Now;
                order.NgayCanDi = datetimepickerOrder == null ? DateTime.Now : DateTime.ParseExact(datetimepickerOrder, "yyyy-MM-dd",
                                            new CultureInfo("en-US"),
                                            DateTimeStyles.None);
                order.GhiChu = ghiChu;

                try
                {
                    var id = Insert(order);

                    string tentour = null;
                    int songuoi = 0;
                    foreach (var item in cart)
                    {
                        var orderDetail = new tbl_OrderDetail();
                        orderDetail.TourID = item.Tour.Id;
                        orderDetail.OrderID = id;
                        orderDetail.DonGia = item.Tour.DonGia;
                        orderDetail.SoNguoi = item.SoNguoi;
                        tentour += item.Tour.TenTourTL;
                        songuoi += item.SoNguoi;
                        InsertOrderDetail(orderDetail);
                    }

                    string content = System.IO.File.ReadAllText(Server.MapPath("~/Views/OrderMail/NewOrderTourSendAdmin.cshtml"));
                    content = content.Replace("{{TenKH}}", tenKH);
                    content = content.Replace("{{SoDT}}", soDT);
                    content = content.Replace("{{Email}}", email);
                    content = content.Replace("{{DiaChi}}", diaChi);
                    content = content.Replace("{{TenTour}}", tentour);
                    content = content.Replace("{{SoNguoi}}", songuoi.ToString("N0"));

                    if (admin.Email != null)
                    {
                        string contentCusstom = null;
                        if (CommonConstants.CurrentCulture == null)
                        {
                            contentCusstom = System.IO.File.ReadAllText(Server.MapPath("~/Views/OrderMail/NewOrderTourSendCustom.cshtml"));
                            contentCusstom = contentCusstom.Replace("{{TenTour}}", tentour);
                            new MailHelper().SendMail(order.Email, Resource.lblConfigOderTour, null, contentCusstom, false, false);
                        }
                        else if (CommonConstants.CurrentCulture.Equals("vi"))
                        {
                            contentCusstom = System.IO.File.ReadAllText(Server.MapPath("~/Views/OrderMail/NewOrderTourSendCustom_vi.cshtml"));
                            contentCusstom = contentCusstom.Replace("{{TenTour}}", tentour);
                            new MailHelper().SendMail(order.Email, Resource.lblConfigOderTour, null, contentCusstom, false, false);
                        }
                        else
                        {
                            contentCusstom = System.IO.File.ReadAllText(Server.MapPath("~/Views/OrderMail/NewOrderTourSendCustom_en.cshtml"));
                            contentCusstom = contentCusstom.Replace("{{TenTour}}", tentour);
                            new MailHelper().SendMail(order.Email, Resource.lblConfigOderTour, null, contentCusstom, false, false);
                        }
                        var toEmail = admin.Email;

                        new MailHelper().SendMail(toEmail, "Khách hàng đặt tour mới", tenKH, content, false, true);
                        Session[CommonConstants.CardSession] = null;
                        return RedirectToAction("Success");
                    }
                }
                catch (Exception ex)
                {
                    return RedirectToAction("OrderTourError");
                }
                return RedirectToAction("OrderTourError");
            }
            else
            {
                ViewBag.ValidateOrder = Resource.vbErrorOderTour;
                return View("Index", cart);
            }
        }

        private int Insert(tbl_Orders order)
        {
            try
            {
                db.tbl_Orders.Add(order);
                db.SaveChanges();
                return order.Id;
            }
            catch (Exception ex)
            {
                Console.Write(ex);
                throw;
            }
            
        }

        private bool InsertOrderDetail(tbl_OrderDetail orderdetail)
        {
            try
            {
                db.tbl_OrderDetail.Add(orderdetail);
                db.SaveChanges();
                return true;
            }
            catch (Exception)
            {
                return false;
            }
        }

        public ActionResult Success()
        {
            return View();
        }

        public ActionResult OrderTourError()
        {
            return View();
        }
    }
}

ThaiViet Smile Travel/Controllers/TourController.cs
using System;
using System.Linq;
using System.Web.Mvc;

using PagedList;

using ThaiVietSmileTravel.Models.Framework;

namespace ThaiViet_Smile_Travel.Controllers
{
    public class TourController : BaseController
    {
        private TVSTravelDbContext db = new TVSTravelDbContext();

        // GET: Tour

        public ActionResult Index(int? categoryId, int page = 1, int pageSize = 6)
        {
            try
            {
                var category = db.tbl_Categories
                    .Find(categoryId);
                if (category != null)
                {
                    ViewBag.TitleCategory = category.TenVN;
                    var query = db.tbl_Tour
                        .Where(x => x.CategoryId == categoryId && x.IsActive)
                        .OrderByDescending(x => x.NgayTao)
                        .ToList();
                    var results = query.ToPagedList(page, pageSize);
                    return View(results);
                }
                else
                {
                    return RedirectToAction("NotFound", "Home");
                }
            }
            catch (Exception)
            {
                return RedirectToAction("NotFound", "Home");
            }
            return View();
        }

        public ActionResult Detail(int? id)
        {
            if (id != 0)
            {
                var result = db.tbl_Tour
                    .Where(x => x.Id == id)
                    .FirstOrDefault();
                return View(result);
            }
            else
            {
                return RedirectToAction("NotFound", "Home");
            }
            return View();
        }
    }
}

ThaiViet Smile Travel/Views/Tour/Detail.cshtml
@model ThaiVietSmileTravel.Models.Framework.tbl_Tour

@{
    ViewBag.Title = @ThaiVietSmileTravel.Globalization.Resource.titleTourDetail;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div style="padding-left: 15px;">
    @if (ThaiViet_Smile_Travel.Common.CommonConstants.CurrentCulture == null)
    {
        <h3>@Model.TenTourTL</h3>
    }
    else
    {
        if (ThaiViet_Smile_Travel.Common.CommonConstants.CurrentCulture.Equals("vi"))
        {
            <h3>@Model.TenTourVN</h3>
        }
        else if (ThaiViet_Smile_Travel.Common.CommonConstants.CurrentCulture.Equals("en"))
        {
            <h3>@Model.TenTourEN</h3>
        }
        else
        {
            <h3>@Model.TenTourTL</h3>
        }
    }
</div>


<div class="col-sm-12 col-lg-12 col-md-12">
    <div class="thumbnail">
        <div class="caption">
            <div class="row col-sm-12 col-lg-12 col-md-12">
                <div class="col-sm-6 col-lg-6 col-md-6">
                    <img src="@Model.HinhAnh" style="height: 200px; margin-top: 10px;" />
                </div>
                <div class="col-sm-6 col-lg-6 col-md-6" style="height: 75%; float: left;">

                    <h4>
                        <label>@Model.SoNgay @ThaiVietSmileTravel.Globalization.Resource.lblDay @Model.SoDem @ThaiVietSmileTravel.Globalization.Resource.lblNight</label>
                    </h4>
                    <h4 class="text-item-number">$@Model.DonGia</h4>
                    <a class="btn btn-primary margin-top-button-item" href="@Url.Action("AddItem","Card", new { tourId = Model.Id, soLuong = 1 })">@ThaiVietSmileTravel.Globalization.Resource.btnAddShoping</a>
                </div>
            </div>
            <div class="row col-sm-12 col-lg-12 col-md-12">
                <h3>@ThaiVietSmileTravel.Globalization.Resource.lblTourDetail</h3>
                @if (ThaiViet_Smile_Travel.Common.CommonConstants.CurrentCulture == null)
                {
                    @Html.Raw(@Model.NoiDungTL)
                }
                else
                {
                    if (ThaiViet_Smile_Travel.Common.CommonConstants.CurrentCulture.Equals("vi"))
                    {
                        @Html.Raw(@Model.NoiDungVN)
                    }
                    else if (ThaiViet_Smile_Travel.Common.CommonConstants.CurrentCulture.Equals("en"))
                    {
                        @Html.Raw(@Model.NoiDungEN)
                    }
                    else
                    {
                        @Html.Raw(@Model.NoiDungTL)
                    }
                }
            </div>
        </div>
    </div>
</div>

ThaiViet Smile Travel/Views/Tour/Index.cshtml
@model PagedList.IPagedList<ThaiVietSmileTravel.Models.Framework.tbl_Tour>
@using PagedList.Mvc;
@{
    ViewBag.Title = ThaiVietSmileTravel.Globalization.Resource.TitleCategoryTour;
    Layout = "~/Views/Shared/_Layout.cshtml";
    var checktitle = Model.Count == 0 ? null : Model.First();
}
@if (checktitle != null)
{
    <div style="padding-left: 15px;">
        @if (checktitle.CategoryId == 1)
        {
            <h3>@ThaiVietSmileTravel.Globalization.Resource.TourNorthern</h3>
        }
        else if (checktitle.CategoryId == 2)
        {
            <h3>@ThaiVietSmileTravel.Globalization.Resource.TourCentral</h3>
        }
        else if (checktitle.CategoryId == 3)
        {
            <h3>@ThaiVietSmileTravel.Globalization.Resource.TourSouth</h3>
        }
        else
        {
            <h3>@ThaiVietSmileTravel.Globalization.Resource.TourForeign</h3>
        }
    </div>



    foreach (var item in Model)
    {

        <div class="col-sm-6 col-lg-6 col-md-6">
            <div class="thumbnail">
                <div class="caption">

                    <div class="col-sm-12 col-lg-12 col-md-12">
                        <div class="headitem">
                            @if (ThaiViet_Smile_Travel.Common.CommonConstants.CurrentCulture == null)
                            {
                                <h4>@item.TenTourTL</h4>
                            }
                            else
                            {
                                if (ThaiViet_Smile_Travel.Common.CommonConstants.CurrentCulture.Equals("vi"))
                                {
                                    <h4>@item.TenTourVN</h4>
                                }
                                else if (ThaiViet_Smile_Travel.Common.CommonConstants.CurrentCulture.Equals("en"))
                                {
                                    <h4>@item.TenTourEN</h4>
                                }
                                else
                                {
                                    <h4>@item.TenTourTL</h4>
                                }
                            }
                        </div>

                    </div>
                    <div class="col-sm-12 col-lg-12 col-md-12 caption">
                        <div class="col-sm-7 col-lg-7 col-md-7">
                            <img src="@item.HinhAnh" style="height: 136px; margin-top: 15px;" />
                        </div>
                        <div class="col-sm-5 col-lg-5 col-md-5" style="height: 75%; float: left; margin-top: 15px;">
                                <label style="font-weight: bold; font-size: 16px;">@item.SoNgay @ThaiVietSmileTravel.Globalization.Resource.lblDay @item.SoDem @ThaiVietSmileTravel.Globalization.Resource.lblNight</label>
                            <h4 class="text-item-number">$@item.DonGia</h4>
                            <a class="btn btn-primary margin-top-button-item" href="@Url.Action("AddItem","Card", new { tourId = @item.Id, soLuong = 1 })">@ThaiVietSmileTravel.Globalization.Resource.btnAddShoping</a>
                            <a class="btn btn-warning margin-top-button-item" href="@Url.Action("Detail", "Tour", new{ id = @item.Id})">@ThaiVietSmileTravel.Globalization.Resource.btnDetail</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }

    <div class="col-sm-9 col-lg-9 col-md-9">
        @Html.PagedListPager(Model, page => Url.Action("Index", new { categoryId = checktitle.CategoryId, page }))
    </div>
}
else
{
    <div class="col-sm-12 col-lg-12 col-md-12 alert alert-danger error-contact">
        @ThaiVietSmileTravel.Globalization.Resource.lblNotTour
    </div>
}